name: VisualDisplays
author: wildmaster84
authors: [wildmaster84, anjoismysign]
api-version: 1.19
description: Image And Media Player In Minecraft
main: me.wildmaster84.visualdisplays.VisualDisplays
version: 1.0